documents:
  directory: Documents
  output: Parsed

database:
  host: 100.100.100.100
  port: 5432
  user: postgres
  password: password
  database: postgres

slack:
  bot_token: xoxb-...
  app:token: xapp-...